### ISSUE TITLE
PLEASE READ

### ISSUE THREAD

**Issue by BeastlyGhost** [BeastlyGhost/Forever-Engine-Underscore#31]
Forever Engine Underscore v0.2.2 is currently in a development phase, which means that the main branch won't get any updates until we are finished with it, the project is no longer a solo one, as I got help from a friend which is going to work on the mod support part

2.2 is going to be developed on the [Unstable Branch](https://github.com/BeastlyGhost/Forever-Engine-Underscore/tree/unstable), as it's not really ready to use

stay tuned for updates
and also, help with the project is extremely appreciated, whether it be pull requests, messages on discord or twitter, anything

UPDATE: 2.2 is deprecated, as i'm gonna work on a mods system from scratch, polymod can be limited at times.

**Comment by BlazeTBV** [comment]
Alright
