### ISSUE TITLE
haha guess what new  COMPLITITINGASDIGE ISSUE IHREW IHETGRW HER GWHIRG IHGRE

### ISSUE THREAD

**Issue by BlazeTBV** [BeastlyGhost/Forever-Engine-Underscore#37]
![image](https://user-images.githubusercontent.com/111521802/188452782-05de4ec2-b142-470e-b99f-68fbac159623.png)

**Comment by BeastlyGhost** [comment]
do this

haxelib remove SScript
haxelib git SScript https://github.com/TheWorldMachine/SScript

**Comment by BlazeTBV** [comment]
I forgot to say this but i fixed it by rerunning the setup
