### ISSUE TITLE
Crashing in the Settings menu

### ISSUE THREAD

**Issue by BlazeTBV** [BeastlyGhost/Forever-Engine-Underscore#42]
### Describe your bug here.

When u move around in the settings menu, the game crashes.

### Command Prompt/Terminal logs (if existing)

```bash
This is when i tried to compile in debug 

Critical Error: Uncatchable Throw: Invalid key code: 0.
```

### Steps to Reproduce (if existing)

spam up and down in the preferences menu

### Are you modding a build from source or with Scripts?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No. I just downloaded it and this happens.

**Comment by BeastlyGhost** [comment]
bind the RESET key to anything, it can't be blank on Key 1 or Key 2, else it will crash on debug builds

I can't really fix this, as it's a flixel issue, and [Yoshubs already addressed it too](https://github.com/Yoshubs/Forever-Engine-Legacy/issues/148#issuecomment-1229241182)

**Comment by BeastlyGhost** [comment]
![image](https://user-images.githubusercontent.com/45212377/190253473-be29b5b7-e679-452e-81a9-7e78ca78f6ef.png)
