### ISSUE TITLE
Some options in the main menu disappear when i change the x position

### ISSUE THREAD

**Issue by BlazeTBV** [BeastlyGhost/Forever-Engine-Underscore#47]
### Describe your bug here.

when i change the x position in the main menu to move the objects to the left, freeplay and options disappear.

### Are you modding a build from source or with Scripts?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

MainMenuState.hx

**Comment by BlazeTBV** [comment]
![image](https://user-images.githubusercontent.com/111521802/192318570-77767ead-d8b9-4aa8-b615-ef5173edfe0a.png)

**Comment by BeastlyGhost** [comment]
did you remove screenCenter?

**Comment by BeastlyGhost** [comment]
change options while 
![image](https://user-images.githubusercontent.com/45212377/192363590-b4bb36e3-c3fb-4f64-89d8-77a2ef8dfeb2.png)
using this function, else they won't work

**Comment by BlazeTBV** [comment]
what?? im not always using the latest version. this is how mine looks like
![image](https://user-images.githubusercontent.com/111521802/192517576-f3cd7621-6f94-4aad-bee2-b8bd31652ef7.png)

**Comment by BlazeTBV** [comment]
> change options while ![image](https://user-images.githubusercontent.com/45212377/192363590-b4bb36e3-c3fb-4f64-89d8-77a2ef8dfeb2.png) using this function, else they won't work

![image](https://user-images.githubusercontent.com/111521802/192775860-fabb3576-c74d-45d5-8b0e-d439009c5fbf.png)
this is on the latest version as of makign this comment and its still happening with this code

**Comment by BeastlyGhost** [comment]
![image](https://user-images.githubusercontent.com/45212377/192820263-85f6634a-0ed3-4054-9d36-c8acaa2ba769.png)
delete this line

**Comment by BeastlyGhost** [comment]
i've never had issues setting them up like this

![image](https://user-images.githubusercontent.com/45212377/192820537-826e934b-8497-46e6-9ff6-bcbe405ce296.png)

![image](https://user-images.githubusercontent.com/45212377/192820631-78fcec3a-d0af-489b-b950-056b608cc825.png)
