### ISSUE TITLE
Crash at Start

### ISSUE THREAD

**Issue by BeastlyGhost** [BeastlyGhost/Forever-Engine-Underscore#48]
when using older builds and upgrading to a more recent one, depending on how old your previous build was, it can crash at the start of the game|

![image](https://user-images.githubusercontent.com/45212377/193392488-932b17c8-a378-4120-a350-bfa398017c69.png)

to fix this, go to your AppData folder, go inside `Yoshubs/Forever-Engine/BeastlyGhost`, and delete your `forever-controls.sol` save file

there's not much that can be done to fix this as it's a bug caused by the controls which can't simply be reverted without causing other problems

**Comment by BlazeTBV** [comment]
you should pin this
