### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by BlazeTBV** [BeastlyGhost/Forever-Engine-Underscore#49]
### Describe your problem here.

Friday Night Funkin' v0.2.8
Forever Engine Underscore v0.2.3 B2 ()
base/Controls.hx (line 718)
states/TitleState.hx (line 43)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/BeastlyGhost/Forever-Engine-Underscore

>Crash Handler written by: sqirra-rng

this happened yesterday with the build redownloaded. redownloaded it today and still happening

### Are you modding from scripts or source?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope. Downloaded and compiled.

**Comment by BeastlyGhost** [comment]
press windows+R

type `%appdata%\Roaming\Yoshubs\Forever-EngineBeasflyGhost`

delete `forever-controls.sol`
