### ISSUE TITLE
uh the settins menu is a uh m hm

### ISSUE THREAD

**Issue by BlazeTBV** [BeastlyGhost/Forever-Engine-Underscore#53]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/111521802/195094806-181d1c02-152c-4c17-a28c-7880068a9adc.png)

### Are you modding a build from source or with Scripts?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope. Downloaded and compiled.

**Comment by BeastlyGhost** [comment]
no a bug, just a weird design oddity, I will change selectors later
