### ISSUE TITLE
Null object reference, but i still get into the game?

### ISSUE THREAD

**Issue by BlazeTBV** [BeastlyGhost/Forever-Engine-Underscore#62]
### Describe your bug here.

When i choose a song, i get a null object reference error, but the game doesnt crash. instead the healthbar colors are back to default and same with the icon bop.

### Command Prompt/Terminal logs (if existing)

```bash
literally none
```

### Steps to Reproduce (if existing)

go in a song ig

### Are you modding a build from source or with Scripts?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by BeastlyGhost** [comment]
the script backend is going through major reworks, if you got any null errors with the newest builds, that's why, as for the game not crashing, it is simply because i avoided making scripts actually run if an issue like that happens, it won't crash bit it will show the error

**Comment by BlazeTBV** [comment]
ohhh ok
